//! Tests that detect mutations in `arbitrary_types.rs`.
//!
//! # Design rationale
//!
//! `arbitrary::Unstructured::fill_buffer` reads bytes from the **front** of the buffer
//! and pads with zeros when the buffer is exhausted — it never returns an error.  As a
//! result, the total number of items generated by `take(n)` always equals `n` regardless
//! of buffer size.  This makes count-based tests the most reliable mutation detectors.
//!
//! For types that expose their length through public APIs we check the count directly.
//! For `ArbPubTxMessage`, whose inner [`nssa::public_transaction::Message`] is opaque,
//! we use the borsh-serialised size of a wrapping [`LeeTransaction::Public`] as a proxy.

use crate::arbitrary_types::{
    ArbHashableBlockData, ArbLeeTransaction, ArbPubTxMessage, ArbPublicTransaction, ArbWitnessSet,
};
use arbitrary::{Arbitrary, Unstructured};
use common::transaction::LeeTransaction;

#[test]
fn arb_lee_transaction_zero_byte_selects_public() {
    // fill_buffer reads from the front, so the first byte consumed = 0.
    let buf = vec![0_u8; 4096];
    let mut u = Unstructured::new(&buf);
    let arb = ArbLeeTransaction::arbitrary(&mut u).expect("should succeed");
    assert!(
        matches!(arb.0, LeeTransaction::Public(_)),
        "expected Public variant: with first byte=0 and `% 2`, arm 0 (Public) is selected"
    );
}

#[test]
fn arb_lee_transaction_byte4_selects_public() {
    // Place 4 as the first byte (variant selector); rest are zeros.
    let mut buf = vec![0_u8; 4096];
    buf[0] = 4;
    let mut u = Unstructured::new(&buf);
    let arb = ArbLeeTransaction::arbitrary(&mut u).expect("should succeed");
    assert!(
        matches!(arb.0, LeeTransaction::Public(_)),
        "expected Public variant: `4 % 2 = 0` \u{2192} arm 0; \
         mutant `4 / 2 = 2` or `4 + 2 = 6` maps to `_` \u{2192} ProgramDeployment"
    );
}

/// Generates from all-1 bytes: `1 % 2 = 1` -> `_` -> `ProgramDeployment`.
#[test]
fn arb_lee_transaction_one_byte_selects_program_deployment() {
    let buf = vec![1_u8; 4096];
    let mut u = Unstructured::new(&buf);
    let arb = ArbLeeTransaction::arbitrary(&mut u).expect("should succeed");
    assert!(
        matches!(arb.0, LeeTransaction::ProgramDeployment(_)),
        "expected ProgramDeployment variant with first byte=1"
    );
}

/// Generates `ArbHashableBlockData` from all-255 bytes and asserts `transactions.len() <= 7`.
#[test]
fn arb_hashable_block_data_tx_count_bounded() {
    let buf = vec![255_u8; 50_000];
    let mut u = Unstructured::new(&buf);
    let arb = ArbHashableBlockData::arbitrary(&mut u)
        .expect("ArbHashableBlockData::arbitrary should succeed with a large all-255 buffer");
    assert!(
        arb.0.transactions.len() <= 7,
        "expected at most 7 transactions (% 8), got {} \
         (mutation: % replaced by / or + on line 248 of arbitrary_types.rs)",
        arb.0.transactions.len()
    );
}

/// Generates `ArbWitnessSet` from all-255 bytes and asserts pair count <= 3.
#[test]
fn arb_witness_set_pair_count_bounded() {
    let buf = vec![255_u8; 50_000];
    let mut u = Unstructured::new(&buf);
    let arb = ArbWitnessSet::arbitrary(&mut u)
        .expect("ArbWitnessSet::arbitrary should succeed with a large all-255 buffer");
    let pair_count = arb.0.signatures_and_public_keys().len();
    assert!(
        pair_count <= 3,
        "expected at most 3 witness pairs (% 4), got {pair_count} \
         (mutation: % replaced by / or + on line 173 of arbitrary_types.rs)"
    );
}

/// Checks the borsh-encoded size of a `LeeTransaction::Public` wrapping an
/// `ArbPubTxMessage` generated from a buffer where the len-selector byte = 255.
#[test]
fn arb_pub_tx_message_account_count_bounded_via_borsh() {
    // Bytes 0-31: zeros for program_id ([u32; 8] via fill_buffer reads 32 bytes).
    // Byte 32: 255 — this is the len-selector byte.  255 % 8 = 7 (correct) vs 255 / 8 = 31 (mutant).
    // Bytes 33+: zeros so Vec<u32> (instruction_data) produces 0 elements (last byte = 0).
    let mut buf = vec![0_u8; 2000];
    buf[32] = 255;

    let mut u = Unstructured::new(&buf);
    let msg =
        ArbPubTxMessage::arbitrary(&mut u).expect("ArbPubTxMessage::arbitrary should succeed");

    // Wrap in a real PublicTransaction to enable borsh serialisation.
    let mut u_witness = Unstructured::new(&[0_u8; 10]);
    let witness = ArbWitnessSet::arbitrary(&mut u_witness)
        .expect("ArbWitnessSet::arbitrary should succeed with zero bytes (n=0)");

    let tx = LeeTransaction::Public(nssa::public_transaction::PublicTransaction::new(
        msg.0, witness.0,
    ));
    let borsh_bytes = borsh::to_vec(&tx).expect("borsh serialization should succeed");

    // With 7 accounts the message borsh-encodes to ~380 bytes; the whole transaction to ~400 bytes.
    // With 31 accounts the message encodes to ~1540 bytes.
    // Using 800 as a conservative threshold clearly separates the two cases.
    assert!(
        borsh_bytes.len() < 800,
        "borsh-encoded size {} bytes exceeds threshold: too many accounts in message \
         (% 8 may have been replaced with / 8 or + 8 on line 144 of arbitrary_types.rs)",
        borsh_bytes.len()
    );
}

/// Additional check: with an all-zero buffer the `ArbPubTxMessage` generates a
/// message with 0 accounts (`0 % 8 = 0`).  This verifies the zero case.
#[test]
fn arb_pub_tx_message_zero_accounts_with_zero_selector() {
    // All zeros: program_id = all 0, len selector byte = 0.
    // 0 % 8 = 0 (correct), 0 + 8 = 8 (+ mutant).
    let buf = vec![0_u8; 500];
    let mut u = Unstructured::new(&buf);
    let msg =
        ArbPubTxMessage::arbitrary(&mut u).expect("ArbPubTxMessage::arbitrary should succeed");

    let mut u_witness = Unstructured::new(&[0_u8; 10]);
    let witness = ArbWitnessSet::arbitrary(&mut u_witness).expect("witness should succeed");

    let tx = LeeTransaction::Public(nssa::public_transaction::PublicTransaction::new(
        msg.0, witness.0,
    ));
    let borsh_bytes = borsh::to_vec(&tx).expect("borsh serialization should succeed");

    // With 0 accounts borsh size is minimal (~50 bytes for empty message + envelope).
    // With 8 accounts (+ mutant) borsh size > 400 bytes.
    assert!(
        borsh_bytes.len() < 300,
        "borsh-encoded size {} bytes too large for zero-account message \
         (% 8 may have been replaced with + 8 on line 144 of arbitrary_types.rs)",
        borsh_bytes.len()
    );
}

/// Verifies that `ArbPublicTransaction::arbitrary` completes without error.
#[test]
fn arb_public_transaction_smoke() {
    let buf = vec![0_u8; 4096];
    let mut u = Unstructured::new(&buf);
    let _ = ArbPublicTransaction::arbitrary(&mut u).expect("should succeed");
}
